version: "3.7"

services:
  db:
    image: postgres:14.5-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    expose:
      - 5432

  backend:
    build:
      context: ./aviate
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    links:
      - db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
