# Generated by Django 4.1.1 on 2022-09-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="academic",
            old_name="company",
            new_name="institute",
        ),
        migrations.RemoveField(
            model_name="academic",
            name="role",
        ),
        migrations.AlterField(
            model_name="academic",
            name="currently_working",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="work",
            name="currently_working",
            field=models.BooleanField(default=False),
        ),
    ]
