# Generated by Django 4.1.1 on 2022-09-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0005_application_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="feedback",
            field=models.TextField(default=""),
        ),
    ]
