# Generated by Django 4.1.1 on 2022-09-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0006_alter_application_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academic",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
