# Generated by Django 4.1.1 on 2022-09-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0009_application_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes"),
        ),
    ]
